### ISSUE TITLE
preface.tex not referenced

### ISSUE THREAD

**Issue by skreutzer** [Peeragogy/peeragogy-handbook#13]
$/en/preface.tex isn't referenced in $/en/peeragogy-shell.tex and instead contains a copy of the text of its own. Furthermore, the latter contains another copy that's commented out.

**Comment by holtzermann17** [comment]
This might be an example where we want to change the markup (namely, by centering the image) as per https://github.com/Peeragogy/Peeragogy.github.io/issues/23, but that's a separate issue, so I have closed this one.
