### ISSUE TITLE
Remove .tex files that are checked in

### ISSUE THREAD

**Issue by skreutzer** [Peeragogy/peeragogy-handbook#8]
This repository contains *.tex files which are checked in. They seem to be an outdated snapshot, probably intended to allow the repository to generate a PDF even if no new version was obtained from the Markdown sources. Additionally, the plan might have been to archive the *.tex files for specific versions of PDFs, while the Markdown source may move on all the time. It could also just have been a checkin accident.

The question here is if the repository needs to contain any of the generated *.tex files anyway, because they need to be updated and maintained and outdate quickly, and if snapshots should be saved, one could easily package a release, as there's not really a point for version-controlling what's automatically generated. Some additional *.tex files that are specific to the book (front matter etc.) may still remain being managed in this repository (as there might not be a large interest in having only one repository for the handbook that contains the Markdown sources, website resources and PDF generation files as well).

Can the generated *.tex files be deleted (if so, this issue is for deleting them) or do they need to be updated according to the Markdown sources (if so, to which version/commit)?

**Comment by holtzermann17** [comment]
What I expect is that the repository has been processed from markdown +
then some further additional by hand changes applied to get everything to
look nice. It would be good if there was a nice fully automated build
solution, but is this going to be possible…?  I am not sure right now.
What we should probably do is keep this ticket open, and try doing an
automated build to see how that goes.

**Comment by skreutzer** [comment]
Isn't the problem that with a moving source, the print generation is

1. always loosing manual custom adjustments anyway (have to be re-done the more the source moves ahead)?
2. misleading in the README and repository concept, where it instructs/recommend to update from the source, which potentially might not work, and should instead focus on building from checked-in snapshot (+ potentially adjusted) .tex files, with a separate workflow to update the entire repository to a new version/snapshot including manual + tech tasks, where it currently seems to be intended to generate from source any time?
3. preventing peers who don't know how to do the adjustments themselves from generating a PDF of the current version?

In general and especially for projects like this, I'm always for automatic generation because doing it manually simply isn't an option with an always-moving source, where there's no (need for) a particular fixed version to be generated (and not all the others equally just as well) and no single entity exclusively doing the generation, and really no valid reason why there should be a long publication cycle while technology theoretically would allow us (and everybody) to do "continuous integration/publication" where hypothetically every checkin updates the PDFs that get automatically uploaded to the/several print-on-demand providers, maybe the contributor together with the checkin already ordering a copy of the part or entire book, for forks as well. And also for every peer/user/reader, to generate and order any version, commit or custom arrangement with a single click basically.

In practice, this doesn't really work well enough yet because of the problem of the paper medium and LaTeX, and some more work would be needed to eventually overcome these and make it work all the time. Beyond LaTeX, other generators could be used too, as they tend to avoid some of the LaTeX-specific problems, but then on the other hand usually they need more work to support the required feature set similar to LaTeX – similar to text/hypertext + media/hypermedia capabilities, I don't see a reason why there shouldn't be improvement in typesetting technology on the computer, just because it's not fancy, new or cool any more.

So what I usually do is to set up an automatic build (I try to keep improving), which may turn out well or well enough for some use cases, and otherwise serves as the current basis do develop customized releases from, then save/archive the adjusted .tex files together with the release (as in libre-free licensing and copyleft, these would be the source code for the PDF and printed book, with the latter being "binary distribution"), and via diff, one can always find out what manual changes were applied (if these need to re-applied to new source versions or aren't needed any more, as one is loosing all of them when updating from source anyway). Ideally, I hoped to eventually get/build a system that would keep track of these adjustments and automatically re-apply them to new sources, or help with merging, as we're used to in software development already. This benefits a lot if informed by the actual version history and little steps and small merges instead of big heuristical diffs of long release cycles.

None of this needs to be of any relevance for the Peeragogy Handbook, I'm currently just trying to fix this particular repository because it doesn't build the way it is with the old sources checked in, it doesn't build updated from the new source, so I'm not really sure about it's purpose or what purpose it should get. In peer spirit, I (and everybody else) could just retrieve the sources and generate PDFs from it in various ways without this repository, but maybe it can be maintained as a useful and easy offer by the Peeragogy project so there's always the option to just use this (or fork off customizations from it, with this repository as a basis) in comparison to the other option that always exists, starting something else from scratch.

**Comment by holtzermann17** [comment]
Totally agree with this plan.  (1) Get the repo into a consistent state so
that it builds, and (2) make it possible to build a basically presentable
PDF using LaTeX and existing automation tools, and then (3) figure out how
to make a fancy "upgraded" PDF version that can import any special changes
that we want to add. If we do (1) and (2) first, we can deal with (3)
later.

It's a pity I left the repo in an inconsistent state, but last time around
I was the only person working on the code and probably made changes on my
local machine that I forgot to upload.  I can look for them at some point,
but won't have access to the old hard drives until the end of the month
because I'm away from home.

By the way, the reason I named my hypertext project "Arxana" -- besides the
obvious reference to Xanadu -- is that there is a city in the US called
Texarkana, so it was also implicitly a reference to TeX.  Ideally Arxana
would be able to handle the kind of moving+merging problems you've
described.

**Comment by daytripper** [comment]
I was planning on using Adobe InDesign to create the PDF. What have I been
missing?

**Comment by holtzermann17** [comment]
Hm...! Let’s discuss on the 22nd. And it is good to have multiple
viable options!

**Comment by skreutzer** [comment]
I don't see how the use of Adobe InDesign to create one/"the" PDF affects this issue or repository, does it? :-)

Agree on (1) and (2) with (3)-type things as a potentially small or large range of secondary activities, and no need to consider leaving the repository some time ago in this or that state "a pity", it seems no peer even bothered to file an issue or complain, let alone try using or even improving it since then. And it's not beyond repair at all, just a little cleaning here and there.

**Comment by skreutzer** [comment]
New tasks for this issue:

- Remove .tex files from this repository that get automatically generated from the current Markdown sources in the Peeragogy.github.io repository. .tex files will be provided via a GitHub release to be generated without dependencies except XeLaTeX.
- Consider the creation of a new repository named "peeragogy-mixin" for manual tweaks/adjustments to the automatically generated .tex files, or to reconstruct these from the diff based on the GitHub release of manually adjusted .tex files, or add to this repository special files or instructions on what to manually modify (keep in mind that Markdown source changes can invalidate everything that previously has been tweaked this way, and the currently checked in .tex files are fairly outdated).
- Decide with what to do about body/content .tex files (not just front matter) of this repository that are referenced for PDF generation (and in part seem to have been printed in the book) instead of the .tex files generated from Markdown - should they get a Markdown source that's not referenced in the index.html spine of the Peeragogy.github.io repository (therefore not linked on the live GitHub Page, but still online on the web despite they're exclusively for print), or remain in this repository with resources that are needed for print only?

**Comment by holtzermann17** [comment]
At least for now, I don't think we should remove the checked in files.  The files will allow people to rebuild without installing dependencies.  Also, there may be multiple different versions checked in.

We could revisit this if and when we have full automation for builds.

**Comment by skreutzer** [comment]
XeLaTeX is a dependency, isn't it? Wasn't the suggestion to bundle/publish generated .tex files as GitHub releases, instead of duplicating the text over two repositories in many versions? Don't we have fully automated builds already?
